influxdb:
  image: influxdb:1.5.2
  container_name: influxdb
  restart: always
  ports:
    - "8083:8083"
    - "8086:8086"
    - "8090:8090"
  env_file:
    - 'env.influxdb'
  volumes:
    # Data persistency
    # sudo mkdir -p /srv/docker/influxdb/data
    - /srv/docker/influxdb/data:/var/lib/influxdb

telegraf:
  image: telegraf:1.6.1
  container_name: telegraf
  restart: always
  links:
    - influxdb
  volumes:
    - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro

grafana:
  image: grafana/grafana:5.1.0
  container_name: grafana
  restart: always
  ports:
    - "3000:3000"
  env_file:
    - 'env.grafana'
  links:
    - influxdb
